### ISSUE TITLE
Evoload links are not resolving

### ISSUE THREAD

**Issue by tetzy** [jsergio123/script.module.resolveurl.xxx#15]
For the past few weeks, I've been getting the same "Evoload link could not be resolved" error when I attempt to download files. 

I'm hoping you can assist. Thanks.

**Comment by Gujal00** [comment]
The evoload test embeds that I have work fine. Can you provide a nonworking evoload embed link so that I can take a look

Also Evoload is part of ResolveURL and is not one of Adult resolvers, please raise the issue in the correct code repository
`https://github.com/jsergio123/script.module.resolveurl/issues`

**Comment by Gujal00** [comment]
No response, closing
